# Generated by Django 5.2.8 on 2025-11-14 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier from Person domain object",
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("MEMBER", "Member"), ("LEAD", "Lead")],
                        default="MEMBER",
                        help_text="User's role in the system",
                        max_length=10,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Person's full name", max_length=100),
                ),
                (
                    "reputation_score",
                    models.IntegerField(
                        default=0, help_text="Current reputation score"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "person_profiles",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "activity_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Activity name", max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Detailed activity description"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        help_text="Points awarded for completing this activity"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the activity is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead_person",
                    models.ForeignKey(
                        help_text="Person who created this activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_activities",
                        to="django_app.personprofile",
                    ),
                ),
            ],
            options={
                "db_table": "activities",
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "action_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the action performed"),
                ),
                (
                    "proof_hash",
                    models.CharField(help_text="Blockchain proof hash", max_length=66),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("VALIDATED", "Validated"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SUBMITTED",
                        help_text="Current status of the action",
                        max_length=10,
                    ),
                ),
                (
                    "validation_notes",
                    models.TextField(
                        blank=True, help_text="Notes from validation process"
                    ),
                ),
                (
                    "points_awarded",
                    models.PositiveIntegerField(
                        blank=True, help_text="Points awarded if validated", null=True
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        help_text="Activity this action relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="django_app.activity",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person who submitted this action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="django_app.personprofile",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who validated this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_actions",
                        to="django_app.personprofile",
                    ),
                ),
            ],
            options={
                "db_table": "actions",
            },
        ),
        migrations.AddIndex(
            model_name="personprofile",
            index=models.Index(
                fields=["person_id"], name="person_prof_person__eb223f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="personprofile",
            index=models.Index(fields=["role"], name="person_prof_role_e42c7e_idx"),
        ),
        migrations.AddIndex(
            model_name="personprofile",
            index=models.Index(
                fields=["reputation_score"], name="person_prof_reputat_85b384_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["is_active"], name="activities_is_acti_cff4bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["created_at"], name="activities_created_78a0e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["lead_person"], name="activities_lead_pe_5345a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["status"], name="actions_status_bfb800_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["person"], name="actions_person__9a7d6e_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(fields=["activity"], name="actions_activit_c62c10_idx"),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["submitted_at"], name="actions_submitt_febc7c_idx"
            ),
        ),
    ]
