# Generated by Django 4.2.26 on 2025-11-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='blockchain_action_id',
            field=models.BigIntegerField(blank=True, help_text='Action ID from the blockchain contract', null=True),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['blockchain_action_id'], name='actions_blockch_55e068_idx'),
        ),
    ]
